base:
  DO_JEDIATMVAR: "NO"
  DO_JEDIATMENS: "NO"
  DO_JEDIOCNVAR: "NO"
  DO_JEDISNOWDA: "NO"
  DO_MERGENSST: "NO"
  DO_BUFRSND: "NO"
  DO_GEMPAK: "NO"
  DO_AWIPS: "NO"
  FLTFILEGFS: "postxconfig-NT-GEFS.txt"
  FLTFILEGFSF00: "postxconfig-NT-GEFS-F00.txt"
  KEEPDATA: "NO" 
  FHMAX_GFS: 120
  FHMAX_HF_GFS: 0
  REPLAY_ICS: "NO"
fcst:
  TYPE: "nh"
  MONO: "non-mono"
